<a href="https://colab.research.google.com/github/Saifullah785/machine-learning-engineer-roadmap/blob/main/Lecture_54_mini_batch_gradient_from_scratch/Lecture_54_mini_batch_gradient_descent_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
# Import necessary libraries for data loading, model training, and evaluation

from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [75]:
# Load the diabetes dataset

X,y = load_diabetes(return_X_y=True)

In [76]:
# Print the shapes of the feature matrix and target vector
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [77]:
# Split the dataset into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [78]:
# Initialize and train a Linear Regression model
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [79]:
# Print the coefficients and intercept of the trained Linear Regression model
print(reg.coef_)
print(reg.intercept_)


[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [80]:
# Make predictions using the trained Linear Regression model and calculate the R2 score
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568968

In [81]:
# Define a custom Mini-Batch Gradient Descent Regressor class
import random
class MBGDRegressor:
  def __init__(self,batch_size,learning_rate=0.01,epochs=100):
    self.coef_ = None
    self.intercept_ = None
    self.lr = learning_rate
    self.epochs = epochs
    self.batch_size = batch_size

  # Method to train the model using gradient descent
  def fit(self,X_train,y_train):

     # Initialize coefficients and intercept

    self.intercept_ = 0

    self.coef_ = np.ones(X_train.shape[1])


    # Iterate through epochs to update coefficients and intercept
    for i in range(self.epochs):

        for j in range(int(X_train.shape[0]/self.batch_size)):

            # update all the coef and the intecept
            idx = random.sample(range(X_train.shape[0]),self.batch_size)

            y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_

            # print("Shape of y_hat",y_hat.shape)

            intercept_der = -2 * np.mean(y_train[idx] - y_hat)

            self.intercept_ = self.intercept_ - (self.lr * intercept_der)

            coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
            self.coef_ = self.coef_ - (self.lr * coef_der)


    print(self.intercept_,self.coef_)

  # Method to make predictions

  def predict(self,X_test):

    return np.dot(X_test,self.coef_) + self.intercept_

In [82]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [83]:
mbr.fit(X_train,y_train)

150.21967803555324 [  30.23271331 -138.81824812  459.07999764  304.3761544   -22.23087914
  -90.75319829 -193.42974491  114.63781627  409.32062974  118.80214131]


In [84]:
y_pred = mbr.predict(X_test)

In [85]:
r2_score(y_test,y_pred)

0.45224866919382056

In [86]:
from sklearn.linear_model import SGDRegressor

In [87]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [88]:
batch_size = 35
for i in range(100):
  idx = random.sample(range(X_train.shape[0]),batch_size)
  sgd.partial_fit(X_train[idx],y_train[idx])

In [89]:
sgd.coef_

array([  58.78351202,  -60.16747282,  348.92318006,  246.36799834,
         21.66347893,  -31.79984407, -156.14004041,  118.38533051,
        327.925642  ,  134.95620208])

In [90]:
sgd.intercept_

array([140.95242358])

In [91]:
y_pred = sgd.predict(X_test)

In [92]:
r2_score(y_test,y_pred)

0.4056769781416014

In [93]:
import random
random.sample(range(1,100),10)

[44, 14, 63, 67, 11, 35, 31, 93, 5, 19]

In [94]:
X_train[[64, 50, 75, 8, 62, 34, 3, 29, 24, 54]]

array([[ 0.04170844,  0.05068012,  0.07139652,  0.00810098,  0.03833367,
         0.01590929, -0.01762938,  0.03430886,  0.07340696,  0.08590655],
       [ 0.07440129, -0.04464164,  0.03151747,  0.10105796,  0.04658939,
         0.03689023,  0.01550536, -0.00259226,  0.03365381,  0.04448548],
       [ 0.01628068, -0.04464164, -0.02452876,  0.03564379, -0.00707277,
        -0.00319277, -0.01394774, -0.00259226,  0.01556846,  0.01549073],
       [-0.08179786,  0.05068012,  0.04229559, -0.01944183,  0.03970963,
         0.05755803, -0.06917231,  0.1081111 ,  0.04719048, -0.03835666],
       [ 0.03081083,  0.05068012,  0.05954058,  0.0563009 , -0.02220825,
         0.00119131, -0.03235593, -0.00259226, -0.02479543, -0.01764613],
       [-0.02730979,  0.05068012,  0.06061839,  0.04941519,  0.08511607,
         0.08636769, -0.00290283,  0.03430886,  0.03781053,  0.04862759],
       [-0.02367725, -0.04464164,  0.04552903,  0.09072941, -0.01808039,
        -0.03544706,  0.07072993, -0.03949338